export const countries = [
  {
    Country: "Afghanistan",
    "Alpha-2 code": "AF",
    "Alpha-3 code": "AFG",
    "Numeric code": 4,
    Latitude: 33,
    Longitude: 65,
  },
  {
    Country: "Åland Islands",
    "Alpha-2 code": "AX",
    "Alpha-3 code": "ALA",
    "Numeric code": 248,
    Latitude: 60.116667,
    Longitude: 19.9,
  },
  {
    Country: "Albania",
    "Alpha-2 code": "AL",
    "Alpha-3 code": "ALB",
    "Numeric code": 8,
    Latitude: 41,
    Longitude: 20,
  },
  {
    Country: "Algeria",
    "Alpha-2 code": "DZ",
    "Alpha-3 code": "DZA",
    "Numeric code": 12,
    Latitude: 28,
    Longitude: 3,
  },
  {
    Country: "American Samoa",
    "Alpha-2 code": "AS",
    "Alpha-3 code": "ASM",
    "Numeric code": 16,
    Latitude: -14.3333,
    Longitude: -170,
  },
  {
    Country: "Andorra",
    "Alpha-2 code": "AD",
    "Alpha-3 code": "AND",
    "Numeric code": 20,
    Latitude: 42.5,
    Longitude: 1.6,
  },
  {
    Country: "Angola",
    "Alpha-2 code": "AO",
    "Alpha-3 code": "AGO",
    "Numeric code": 24,
    Latitude: -12.5,
    Longitude: 18.5,
  },
  {
    Country: "Anguilla",
    "Alpha-2 code": "AI",
    "Alpha-3 code": "AIA",
    "Numeric code": 660,
    Latitude: 18.25,
    Longitude: -63.1667,
  },
  {
    Country: "Antarctica",
    "Alpha-2 code": "AQ",
    "Alpha-3 code": "ATA",
    "Numeric code": 10,
    Latitude: -90,
    Longitude: 0,
  },
  {
    Country: "Antigua and Barbuda",
    "Alpha-2 code": "AG",
    "Alpha-3 code": "ATG",
    "Numeric code": 28,
    Latitude: 17.05,
    Longitude: -61.8,
  },
  {
    Country: "Argentina",
    "Alpha-2 code": "AR",
    "Alpha-3 code": "ARG",
    "Numeric code": 32,
    Latitude: -34,
    Longitude: -64,
  },
  {
    Country: "Armenia",
    "Alpha-2 code": "AM",
    "Alpha-3 code": "ARM",
    "Numeric code": 51,
    Latitude: 40,
    Longitude: 45,
  },
  {
    Country: "Aruba",
    "Alpha-2 code": "AW",
    "Alpha-3 code": "ABW",
    "Numeric code": 533,
    Latitude: 12.5,
    Longitude: -69.9667,
  },
  {
    Country: "Australia",
    "Alpha-2 code": "AU",
    "Alpha-3 code": "AUS",
    "Numeric code": 36,
    Latitude: -27,
    Longitude: 133,
  },
  {
    Country: "Austria",
    "Alpha-2 code": "AT",
    "Alpha-3 code": "AUT",
    "Numeric code": 40,
    Latitude: 47.3333,
    Longitude: 13.3333,
  },
  {
    Country: "Azerbaijan",
    "Alpha-2 code": "AZ",
    "Alpha-3 code": "AZE",
    "Numeric code": 31,
    Latitude: 40.5,
    Longitude: 47.5,
  },
  {
    Country: "Bahamas",
    "Alpha-2 code": "BS",
    "Alpha-3 code": "BHS",
    "Numeric code": 44,
    Latitude: 24.25,
    Longitude: -76,
  },
  {
    Country: "Bahrain",
    "Alpha-2 code": "BH",
    "Alpha-3 code": "BHR",
    "Numeric code": 48,
    Latitude: 26,
    Longitude: 50.55,
  },
  {
    Country: "Bangladesh",
    "Alpha-2 code": "BD",
    "Alpha-3 code": "BGD",
    "Numeric code": 50,
    Latitude: 24,
    Longitude: 90,
  },
  {
    Country: "Barbados",
    "Alpha-2 code": "BB",
    "Alpha-3 code": "BRB",
    "Numeric code": 52,
    Latitude: 13.1667,
    Longitude: -59.5333,
  },
  {
    Country: "Belarus",
    "Alpha-2 code": "BY",
    "Alpha-3 code": "BLR",
    "Numeric code": 112,
    Latitude: 53,
    Longitude: 28,
  },
  {
    Country: "Belgium",
    "Alpha-2 code": "BE",
    "Alpha-3 code": "BEL",
    "Numeric code": 56,
    Latitude: 50.8333,
    Longitude: 4,
  },
  {
    Country: "Belize",
    "Alpha-2 code": "BZ",
    "Alpha-3 code": "BLZ",
    "Numeric code": 84,
    Latitude: 17.25,
    Longitude: -88.75,
  },
  {
    Country: "Benin",
    "Alpha-2 code": "BJ",
    "Alpha-3 code": "BEN",
    "Numeric code": 204,
    Latitude: 9.5,
    Longitude: 2.25,
  },
  {
    Country: "Bermuda",
    "Alpha-2 code": "BM",
    "Alpha-3 code": "BMU",
    "Numeric code": 60,
    Latitude: 32.3333,
    Longitude: -64.75,
  },
  {
    Country: "Bhutan",
    "Alpha-2 code": "BT",
    "Alpha-3 code": "BTN",
    "Numeric code": 64,
    Latitude: 27.5,
    Longitude: 90.5,
  },
  {
    Country: "Bolivia, Plurinational State of",
    "Alpha-2 code": "BO",
    "Alpha-3 code": "BOL",
    "Numeric code": 68,
    Latitude: -17,
    Longitude: -65,
  },
  {
    Country: "Bolivia",
    "Alpha-2 code": "BO",
    "Alpha-3 code": "BOL",
    "Numeric code": 68,
    Latitude: -17,
    Longitude: -65,
  },
  {
    Country: "Bonaire, Sint Eustatius and Saba",
    "Alpha-2 code": "BQ",
    "Alpha-3 code": "BES",
    "Numeric code": 535,
    Latitude: 12.183333,
    Longitude: -68.233333,
  },
  {
    Country: "Bosnia and Herzegovina",
    "Alpha-2 code": "BA",
    "Alpha-3 code": "BIH",
    "Numeric code": 70,
    Latitude: 44,
    Longitude: 18,
  },
  {
    Country: "Botswana",
    "Alpha-2 code": "BW",
    "Alpha-3 code": "BWA",
    "Numeric code": 72,
    Latitude: -22,
    Longitude: 24,
  },
  {
    Country: "Bouvet Island",
    "Alpha-2 code": "BV",
    "Alpha-3 code": "BVT",
    "Numeric code": 74,
    Latitude: -54.4333,
    Longitude: 3.4,
  },
  {
    Country: "Brazil",
    "Alpha-2 code": "BR",
    "Alpha-3 code": "BRA",
    "Numeric code": 76,
    Latitude: -10,
    Longitude: -55,
  },
  {
    Country: "British Indian Ocean Territory",
    "Alpha-2 code": "IO",
    "Alpha-3 code": "IOT",
    "Numeric code": 86,
    Latitude: -6,
    Longitude: 71.5,
  },
  {
    Country: "Brunei Darussalam",
    "Alpha-2 code": "BN",
    "Alpha-3 code": "BRN",
    "Numeric code": 96,
    Latitude: 4.5,
    Longitude: 114.6667,
  },
  {
    Country: "Brunei",
    "Alpha-2 code": "BN",
    "Alpha-3 code": "BRN",
    "Numeric code": 96,
    Latitude: 4.5,
    Longitude: 114.6667,
  },
  {
    Country: "Bulgaria",
    "Alpha-2 code": "BG",
    "Alpha-3 code": "BGR",
    "Numeric code": 100,
    Latitude: 43,
    Longitude: 25,
  },
  {
    Country: "Burkina Faso",
    "Alpha-2 code": "BF",
    "Alpha-3 code": "BFA",
    "Numeric code": 854,
    Latitude: 13,
    Longitude: -2,
  },
  {
    Country: "Burma",
    "Alpha-2 code": "MM",
    "Alpha-3 code": "MMR",
    "Numeric code": 104,
    Latitude: 22,
    Longitude: 98,
  },
  {
    Country: "Burundi",
    "Alpha-2 code": "BI",
    "Alpha-3 code": "BDI",
    "Numeric code": 108,
    Latitude: -3.5,
    Longitude: 30,
  },
  {
    Country: "Cambodia",
    "Alpha-2 code": "KH",
    "Alpha-3 code": "KHM",
    "Numeric code": 116,
    Latitude: 13,
    Longitude: 105,
  },
  {
    Country: "Cameroon",
    "Alpha-2 code": "CM",
    "Alpha-3 code": "CMR",
    "Numeric code": 120,
    Latitude: 6,
    Longitude: 12,
  },
  {
    Country: "Canada",
    "Alpha-2 code": "CA",
    "Alpha-3 code": "CAN",
    "Numeric code": 124,
    Latitude: 60,
    Longitude: -95,
  },
  {
    Country: "Cape Verde",
    "Alpha-2 code": "CV",
    "Alpha-3 code": "CPV",
    "Numeric code": 132,
    Latitude: 16,
    Longitude: -24,
  },
  {
    Country: "Cayman Islands",
    "Alpha-2 code": "KY",
    "Alpha-3 code": "CYM",
    "Numeric code": 136,
    Latitude: 19.5,
    Longitude: -80.5,
  },
  {
    Country: "Central African Republic",
    "Alpha-2 code": "CF",
    "Alpha-3 code": "CAF",
    "Numeric code": 140,
    Latitude: 7,
    Longitude: 21,
  },
  {
    Country: "Chad",
    "Alpha-2 code": "TD",
    "Alpha-3 code": "TCD",
    "Numeric code": 148,
    Latitude: 15,
    Longitude: 19,
  },
  {
    Country: "Chile",
    "Alpha-2 code": "CL",
    "Alpha-3 code": "CHL",
    "Numeric code": 152,
    Latitude: -30,
    Longitude: -71,
  },
  {
    Country: "China",
    "Alpha-2 code": "CN",
    "Alpha-3 code": "CHN",
    "Numeric code": 156,
    Latitude: 35,
    Longitude: 105,
  },
  {
    Country: "Christmas Island",
    "Alpha-2 code": "CX",
    "Alpha-3 code": "CXR",
    "Numeric code": 162,
    Latitude: -10.5,
    Longitude: 105.6667,
  },
  {
    Country: "Cocos (Keeling) Islands",
    "Alpha-2 code": "CC",
    "Alpha-3 code": "CCK",
    "Numeric code": 166,
    Latitude: -12.5,
    Longitude: 96.8333,
  },
  {
    Country: "Colombia",
    "Alpha-2 code": "CO",
    "Alpha-3 code": "COL",
    "Numeric code": 170,
    Latitude: 4,
    Longitude: -72,
  },
  {
    Country: "Comoros",
    "Alpha-2 code": "KM",
    "Alpha-3 code": "COM",
    "Numeric code": 174,
    Latitude: -12.1667,
    Longitude: 44.25,
  },
  {
    Country: "Congo, the Democratic Republic of the",
    "Alpha-2 code": "CD",
    "Alpha-3 code": "COD",
    "Numeric code": 180,
    Latitude: 0,
    Longitude: 25,
  },
  {
    Country: "Congo",
    "Alpha-2 code": "CG",
    "Alpha-3 code": "COG",
    "Numeric code": 178,
    Latitude: -1,
    Longitude: 15,
  },
  {
    Country: "Cook Islands",
    "Alpha-2 code": "CK",
    "Alpha-3 code": "COK",
    "Numeric code": 184,
    Latitude: -21.2333,
    Longitude: -159.7667,
  },
  {
    Country: "Costa Rica",
    "Alpha-2 code": "CR",
    "Alpha-3 code": "CRI",
    "Numeric code": 188,
    Latitude: 10,
    Longitude: -84,
  },
  {
    Country: "Côte d'Ivoire",
    "Alpha-2 code": "CI",
    "Alpha-3 code": "CIV",
    "Numeric code": 384,
    Latitude: 8,
    Longitude: -5,
  },
  {
    Country: "Croatia",
    "Alpha-2 code": "HR",
    "Alpha-3 code": "HRV",
    "Numeric code": 191,
    Latitude: 45.1667,
    Longitude: 15.5,
  },
  {
    Country: "Cuba",
    "Alpha-2 code": "CU",
    "Alpha-3 code": "CUB",
    "Numeric code": 192,
    Latitude: 21.5,
    Longitude: -80,
  },
  {
    Country: "Curaçao",
    "Alpha-2 code": "CW",
    "Alpha-3 code": "CUW",
    "Numeric code": 531,
    Latitude: 12.166667,
    Longitude: -68.966667,
  },
  {
    Country: "Cyprus",
    "Alpha-2 code": "CY",
    "Alpha-3 code": "CYP",
    "Numeric code": 196,
    Latitude: 35,
    Longitude: 33,
  },
  {
    Country: "Czech Republic",
    "Alpha-2 code": "CZ",
    "Alpha-3 code": "CZE",
    "Numeric code": 203,
    Latitude: 49.75,
    Longitude: 15.5,
  },
  {
    Country: "Denmark",
    "Alpha-2 code": "DK",
    "Alpha-3 code": "DNK",
    "Numeric code": 208,
    Latitude: 56,
    Longitude: 10,
  },
  {
    Country: "Djibouti",
    "Alpha-2 code": "DJ",
    "Alpha-3 code": "DJI",
    "Numeric code": 262,
    Latitude: 11.5,
    Longitude: 43,
  },
  {
    Country: "Dominica",
    "Alpha-2 code": "DM",
    "Alpha-3 code": "DMA",
    "Numeric code": 212,
    Latitude: 15.4167,
    Longitude: -61.3333,
  },
  {
    Country: "Dominican Republic",
    "Alpha-2 code": "DO",
    "Alpha-3 code": "DOM",
    "Numeric code": 214,
    Latitude: 19,
    Longitude: -70.6667,
  },
  {
    Country: "Ecuador",
    "Alpha-2 code": "EC",
    "Alpha-3 code": "ECU",
    "Numeric code": 218,
    Latitude: -2,
    Longitude: -77.5,
  },
  {
    Country: "Egypt",
    "Alpha-2 code": "EG",
    "Alpha-3 code": "EGY",
    "Numeric code": 818,
    Latitude: 27,
    Longitude: 30,
  },
  {
    Country: "El Salvador",
    "Alpha-2 code": "SV",
    "Alpha-3 code": "SLV",
    "Numeric code": 222,
    Latitude: 13.8333,
    Longitude: -88.9167,
  },
  {
    Country: "Equatorial Guinea",
    "Alpha-2 code": "GQ",
    "Alpha-3 code": "GNQ",
    "Numeric code": 226,
    Latitude: 2,
    Longitude: 10,
  },
  {
    Country: "Eritrea",
    "Alpha-2 code": "ER",
    "Alpha-3 code": "ERI",
    "Numeric code": 232,
    Latitude: 15,
    Longitude: 39,
  },
  {
    Country: "Estonia",
    "Alpha-2 code": "EE",
    "Alpha-3 code": "EST",
    "Numeric code": 233,
    Latitude: 59,
    Longitude: 26,
  },
  {
    Country: "Ethiopia",
    "Alpha-2 code": "ET",
    "Alpha-3 code": "ETH",
    "Numeric code": 231,
    Latitude: 8,
    Longitude: 38,
  },
  {
    Country: "Falkland Islands (Malvinas)",
    "Alpha-2 code": "FK",
    "Alpha-3 code": "FLK",
    "Numeric code": 238,
    Latitude: -51.75,
    Longitude: -59,
  },
  {
    Country: "Faroe Islands",
    "Alpha-2 code": "FO",
    "Alpha-3 code": "FRO",
    "Numeric code": 234,
    Latitude: 62,
    Longitude: -7,
  },
  {
    Country: "Fiji",
    "Alpha-2 code": "FJ",
    "Alpha-3 code": "FJI",
    "Numeric code": 242,
    Latitude: -18,
    Longitude: 175,
  },
  {
    Country: "Finland",
    "Alpha-2 code": "FI",
    "Alpha-3 code": "FIN",
    "Numeric code": 246,
    Latitude: 64,
    Longitude: 26,
  },
  {
    Country: "France",
    "Alpha-2 code": "FR",
    "Alpha-3 code": "FRA",
    "Numeric code": 250,
    Latitude: 46,
    Longitude: 2,
  },
  {
    Country: "French Guiana",
    "Alpha-2 code": "GF",
    "Alpha-3 code": "GUF",
    "Numeric code": 254,
    Latitude: 4,
    Longitude: -53,
  },
  {
    Country: "French Polynesia",
    "Alpha-2 code": "PF",
    "Alpha-3 code": "PYF",
    "Numeric code": 258,
    Latitude: -15,
    Longitude: -140,
  },
  {
    Country: "French Southern Territories",
    "Alpha-2 code": "TF",
    "Alpha-3 code": "ATF",
    "Numeric code": 260,
    Latitude: -43,
    Longitude: 67,
  },
  {
    Country: "Gabon",
    "Alpha-2 code": "GA",
    "Alpha-3 code": "GAB",
    "Numeric code": 266,
    Latitude: -1,
    Longitude: 11.75,
  },
  {
    Country: "Gambia",
    "Alpha-2 code": "GM",
    "Alpha-3 code": "GMB",
    "Numeric code": 270,
    Latitude: 13.4667,
    Longitude: -16.5667,
  },
  {
    Country: "Georgia",
    "Alpha-2 code": "GE",
    "Alpha-3 code": "GEO",
    "Numeric code": 268,
    Latitude: 42,
    Longitude: 43.5,
  },
  {
    Country: "Germany",
    "Alpha-2 code": "DE",
    "Alpha-3 code": "DEU",
    "Numeric code": 276,
    Latitude: 51,
    Longitude: 9,
  },
  {
    Country: "Ghana",
    "Alpha-2 code": "GH",
    "Alpha-3 code": "GHA",
    "Numeric code": 288,
    Latitude: 8,
    Longitude: -2,
  },
  {
    Country: "Gibraltar",
    "Alpha-2 code": "GI",
    "Alpha-3 code": "GIB",
    "Numeric code": 292,
    Latitude: 36.1833,
    Longitude: -5.3667,
  },
  {
    Country: "Greece",
    "Alpha-2 code": "GR",
    "Alpha-3 code": "GRC",
    "Numeric code": 300,
    Latitude: 39,
    Longitude: 22,
  },
  {
    Country: "Greenland",
    "Alpha-2 code": "GL",
    "Alpha-3 code": "GRL",
    "Numeric code": 304,
    Latitude: 72,
    Longitude: -40,
  },
  {
    Country: "Grenada",
    "Alpha-2 code": "GD",
    "Alpha-3 code": "GRD",
    "Numeric code": 308,
    Latitude: 12.1167,
    Longitude: -61.6667,
  },
  {
    Country: "Guadeloupe",
    "Alpha-2 code": "GP",
    "Alpha-3 code": "GLP",
    "Numeric code": 312,
    Latitude: 16.25,
    Longitude: -61.5833,
  },
  {
    Country: "Guam",
    "Alpha-2 code": "GU",
    "Alpha-3 code": "GUM",
    "Numeric code": 316,
    Latitude: 13.4667,
    Longitude: 144.7833,
  },
  {
    Country: "Guatemala",
    "Alpha-2 code": "GT",
    "Alpha-3 code": "GTM",
    "Numeric code": 320,
    Latitude: 15.5,
    Longitude: -90.25,
  },
  {
    Country: "Guernsey",
    "Alpha-2 code": "GG",
    "Alpha-3 code": "GGY",
    "Numeric code": 831,
    Latitude: 49.5,
    Longitude: -2.56,
  },
  {
    Country: "Guinea-Bissau",
    "Alpha-2 code": "GW",
    "Alpha-3 code": "GNB",
    "Numeric code": 624,
    Latitude: 12,
    Longitude: -15,
  },
  {
    Country: "Guinea",
    "Alpha-2 code": "GN",
    "Alpha-3 code": "GIN",
    "Numeric code": 324,
    Latitude: 11,
    Longitude: -10,
  },
  {
    Country: "Guyana",
    "Alpha-2 code": "GY",
    "Alpha-3 code": "GUY",
    "Numeric code": 328,
    Latitude: 5,
    Longitude: -59,
  },
  {
    Country: "Haiti",
    "Alpha-2 code": "HT",
    "Alpha-3 code": "HTI",
    "Numeric code": 332,
    Latitude: 19,
    Longitude: -72.4167,
  },
  {
    Country: "Heard Island and McDonald Islands",
    "Alpha-2 code": "HM",
    "Alpha-3 code": "HMD",
    "Numeric code": 334,
    Latitude: -53.1,
    Longitude: 72.5167,
  },
  {
    Country: "Holy See (Vatican City State)",
    "Alpha-2 code": "VA",
    "Alpha-3 code": "VAT",
    "Numeric code": 336,
    Latitude: 41.9,
    Longitude: 12.45,
  },
  {
    Country: "Honduras",
    "Alpha-2 code": "HN",
    "Alpha-3 code": "HND",
    "Numeric code": 340,
    Latitude: 15,
    Longitude: -86.5,
  },
  {
    Country: "Hong Kong",
    "Alpha-2 code": "HK",
    "Alpha-3 code": "HKG",
    "Numeric code": 344,
    Latitude: 22.25,
    Longitude: 114.1667,
  },
  {
    Country: "Hungary",
    "Alpha-2 code": "HU",
    "Alpha-3 code": "HUN",
    "Numeric code": 348,
    Latitude: 47,
    Longitude: 20,
  },
  {
    Country: "Iceland",
    "Alpha-2 code": "IS",
    "Alpha-3 code": "ISL",
    "Numeric code": 352,
    Latitude: 65,
    Longitude: -18,
  },
  {
    Country: "India",
    "Alpha-2 code": "IN",
    "Alpha-3 code": "IND",
    "Numeric code": 356,
    Latitude: 20,
    Longitude: 77,
  },
  {
    Country: "Indonesia",
    "Alpha-2 code": "ID",
    "Alpha-3 code": "IDN",
    "Numeric code": 360,
    Latitude: -5,
    Longitude: 120,
  },
  {
    Country: "Iran, Islamic Republic of",
    "Alpha-2 code": "IR",
    "Alpha-3 code": "IRN",
    "Numeric code": 364,
    Latitude: 32,
    Longitude: 53,
  },
  {
    Country: "Iraq",
    "Alpha-2 code": "IQ",
    "Alpha-3 code": "IRQ",
    "Numeric code": 368,
    Latitude: 33,
    Longitude: 44,
  },
  {
    Country: "Ireland",
    "Alpha-2 code": "IE",
    "Alpha-3 code": "IRL",
    "Numeric code": 372,
    Latitude: 53,
    Longitude: -8,
  },
  {
    Country: "Isle of Man",
    "Alpha-2 code": "IM",
    "Alpha-3 code": "IMN",
    "Numeric code": 833,
    Latitude: 54.23,
    Longitude: -4.55,
  },
  {
    Country: "Israel",
    "Alpha-2 code": "IL",
    "Alpha-3 code": "ISR",
    "Numeric code": 376,
    Latitude: 31.5,
    Longitude: 34.75,
  },
  {
    Country: "Italy",
    "Alpha-2 code": "IT",
    "Alpha-3 code": "ITA",
    "Numeric code": 380,
    Latitude: 42.8333,
    Longitude: 12.8333,
  },
  {
    Country: "Ivory Coast",
    "Alpha-2 code": "CI",
    "Alpha-3 code": "CIV",
    "Numeric code": 384,
    Latitude: 8,
    Longitude: -5,
  },
  {
    Country: "Jamaica",
    "Alpha-2 code": "JM",
    "Alpha-3 code": "JAM",
    "Numeric code": 388,
    Latitude: 18.25,
    Longitude: -77.5,
  },
  {
    Country: "Japan",
    "Alpha-2 code": "JP",
    "Alpha-3 code": "JPN",
    "Numeric code": 392,
    Latitude: 36,
    Longitude: 138,
  },
  {
    Country: "Jersey",
    "Alpha-2 code": "JE",
    "Alpha-3 code": "JEY",
    "Numeric code": 832,
    Latitude: 49.21,
    Longitude: -2.13,
  },
  {
    Country: "Jordan",
    "Alpha-2 code": "JO",
    "Alpha-3 code": "JOR",
    "Numeric code": 400,
    Latitude: 31,
    Longitude: 36,
  },
  {
    Country: "Kazakhstan",
    "Alpha-2 code": "KZ",
    "Alpha-3 code": "KAZ",
    "Numeric code": 398,
    Latitude: 48,
    Longitude: 68,
  },
  {
    Country: "Kenya",
    "Alpha-2 code": "KE",
    "Alpha-3 code": "KEN",
    "Numeric code": 404,
    Latitude: 1,
    Longitude: 38,
  },
  {
    Country: "Kiribati",
    "Alpha-2 code": "KI",
    "Alpha-3 code": "KIR",
    "Numeric code": 296,
    Latitude: 1.4167,
    Longitude: 173,
  },
  {
    Country: "Korea, Democratic People's Republic of",
    "Alpha-2 code": "KP",
    "Alpha-3 code": "PRK",
    "Numeric code": 408,
    Latitude: 40,
    Longitude: 127,
  },
  {
    Country: "Korea, Republic of",
    "Alpha-2 code": "KR",
    "Alpha-3 code": "KOR",
    "Numeric code": 410,
    Latitude: 37,
    Longitude: 127.5,
  },
  {
    Country: "Kosovo",
    "Alpha-2 code": "XK",
    "Alpha-3 code": "XKX",
    "Numeric code": 95,
    Latitude: 42.583333,
    Longitude: 21,
  },
  {
    Country: "Kuwait",
    "Alpha-2 code": "KW",
    "Alpha-3 code": "KWT",
    "Numeric code": 414,
    Latitude: 29.3375,
    Longitude: 47.6581,
  },
  {
    Country: "Kyrgyzstan",
    "Alpha-2 code": "KG",
    "Alpha-3 code": "KGZ",
    "Numeric code": 417,
    Latitude: 41,
    Longitude: 75,
  },
  {
    Country: "Lao People's Democratic Republic",
    "Alpha-2 code": "LA",
    "Alpha-3 code": "LAO",
    "Numeric code": 418,
    Latitude: 18,
    Longitude: 105,
  },
  {
    Country: "Latvia",
    "Alpha-2 code": "LV",
    "Alpha-3 code": "LVA",
    "Numeric code": 428,
    Latitude: 57,
    Longitude: 25,
  },
  {
    Country: "Lebanon",
    "Alpha-2 code": "LB",
    "Alpha-3 code": "LBN",
    "Numeric code": 422,
    Latitude: 33.8333,
    Longitude: 35.8333,
  },
  {
    Country: "Lesotho",
    "Alpha-2 code": "LS",
    "Alpha-3 code": "LSO",
    "Numeric code": 426,
    Latitude: -29.5,
    Longitude: 28.5,
  },
  {
    Country: "Liberia",
    "Alpha-2 code": "LR",
    "Alpha-3 code": "LBR",
    "Numeric code": 430,
    Latitude: 6.5,
    Longitude: -9.5,
  },
  {
    Country: "Libya",
    "Alpha-2 code": "LY",
    "Alpha-3 code": "LBY",
    "Numeric code": 434,
    Latitude: 25,
    Longitude: 17,
  },
  {
    Country: "Libyan Arab Jamahiriya",
    "Alpha-2 code": "LY",
    "Alpha-3 code": "LBY",
    "Numeric code": 434,
    Latitude: 25,
    Longitude: 17,
  },
  {
    Country: "Liechtenstein",
    "Alpha-2 code": "LI",
    "Alpha-3 code": "LIE",
    "Numeric code": 438,
    Latitude: 47.1667,
    Longitude: 9.5333,
  },
  {
    Country: "Lithuania",
    "Alpha-2 code": "LT",
    "Alpha-3 code": "LTU",
    "Numeric code": 440,
    Latitude: 56,
    Longitude: 24,
  },
  {
    Country: "Luxembourg",
    "Alpha-2 code": "LU",
    "Alpha-3 code": "LUX",
    "Numeric code": 442,
    Latitude: 49.75,
    Longitude: 6.1667,
  },
  {
    Country: "Macao",
    "Alpha-2 code": "MO",
    "Alpha-3 code": "MAC",
    "Numeric code": 446,
    Latitude: 22.1667,
    Longitude: 113.55,
  },
  {
    Country: "Macedonia, the former Yugoslav Republic of",
    "Alpha-2 code": "MK",
    "Alpha-3 code": "MKD",
    "Numeric code": 807,
    Latitude: 41.8333,
    Longitude: 22,
  },
  {
    Country: "Madagascar",
    "Alpha-2 code": "MG",
    "Alpha-3 code": "MDG",
    "Numeric code": 450,
    Latitude: -20,
    Longitude: 47,
  },
  {
    Country: "Malawi",
    "Alpha-2 code": "MW",
    "Alpha-3 code": "MWI",
    "Numeric code": 454,
    Latitude: -13.5,
    Longitude: 34,
  },
  {
    Country: "Malaysia",
    "Alpha-2 code": "MY",
    "Alpha-3 code": "MYS",
    "Numeric code": 458,
    Latitude: 2.5,
    Longitude: 112.5,
  },
  {
    Country: "Maldives",
    "Alpha-2 code": "MV",
    "Alpha-3 code": "MDV",
    "Numeric code": 462,
    Latitude: 3.25,
    Longitude: 73,
  },
  {
    Country: "Mali",
    "Alpha-2 code": "ML",
    "Alpha-3 code": "MLI",
    "Numeric code": 466,
    Latitude: 17,
    Longitude: -4,
  },
  {
    Country: "Malta",
    "Alpha-2 code": "MT",
    "Alpha-3 code": "MLT",
    "Numeric code": 470,
    Latitude: 35.8333,
    Longitude: 14.5833,
  },
  {
    Country: "Marshall Islands",
    "Alpha-2 code": "MH",
    "Alpha-3 code": "MHL",
    "Numeric code": 584,
    Latitude: 9,
    Longitude: 168,
  },
  {
    Country: "Martinique",
    "Alpha-2 code": "MQ",
    "Alpha-3 code": "MTQ",
    "Numeric code": 474,
    Latitude: 14.6667,
    Longitude: -61,
  },
  {
    Country: "Mauritania",
    "Alpha-2 code": "MR",
    "Alpha-3 code": "MRT",
    "Numeric code": 478,
    Latitude: 20,
    Longitude: -12,
  },
  {
    Country: "Mauritius",
    "Alpha-2 code": "MU",
    "Alpha-3 code": "MUS",
    "Numeric code": 480,
    Latitude: -20.2833,
    Longitude: 57.55,
  },
  {
    Country: "Mayotte",
    "Alpha-2 code": "YT",
    "Alpha-3 code": "MYT",
    "Numeric code": 175,
    Latitude: -12.8333,
    Longitude: 45.1667,
  },
  {
    Country: "Mexico",
    "Alpha-2 code": "MX",
    "Alpha-3 code": "MEX",
    "Numeric code": 484,
    Latitude: 23,
    Longitude: -102,
  },
  {
    Country: "Micronesia, Federated States of",
    "Alpha-2 code": "FM",
    "Alpha-3 code": "FSM",
    "Numeric code": 583,
    Latitude: 6.9167,
    Longitude: 158.25,
  },
  {
    Country: "Moldova, Republic of",
    "Alpha-2 code": "MD",
    "Alpha-3 code": "MDA",
    "Numeric code": 498,
    Latitude: 47,
    Longitude: 29,
  },
  {
    Country: "Monaco",
    "Alpha-2 code": "MC",
    "Alpha-3 code": "MCO",
    "Numeric code": 492,
    Latitude: 43.7333,
    Longitude: 7.4,
  },
  {
    Country: "Mongolia",
    "Alpha-2 code": "MN",
    "Alpha-3 code": "MNG",
    "Numeric code": 496,
    Latitude: 46,
    Longitude: 105,
  },
  {
    Country: "Montenegro",
    "Alpha-2 code": "ME",
    "Alpha-3 code": "MNE",
    "Numeric code": 499,
    Latitude: 42,
    Longitude: 19,
  },
  {
    Country: "Montserrat",
    "Alpha-2 code": "MS",
    "Alpha-3 code": "MSR",
    "Numeric code": 500,
    Latitude: 16.75,
    Longitude: -62.2,
  },
  {
    Country: "Morocco",
    "Alpha-2 code": "MA",
    "Alpha-3 code": "MAR",
    "Numeric code": 504,
    Latitude: 32,
    Longitude: -5,
  },
  {
    Country: "Mozambique",
    "Alpha-2 code": "MZ",
    "Alpha-3 code": "MOZ",
    "Numeric code": 508,
    Latitude: -18.25,
    Longitude: 35,
  },
  {
    Country: "Myanmar",
    "Alpha-2 code": "MM",
    "Alpha-3 code": "MMR",
    "Numeric code": 104,
    Latitude: 22,
    Longitude: 98,
  },
  {
    Country: "Namibia",
    "Alpha-2 code": "NA",
    "Alpha-3 code": "NAM",
    "Numeric code": 516,
    Latitude: -22,
    Longitude: 17,
  },
  {
    Country: "Nauru",
    "Alpha-2 code": "NR",
    "Alpha-3 code": "NRU",
    "Numeric code": 520,
    Latitude: -0.5333,
    Longitude: 166.9167,
  },
  {
    Country: "Nepal",
    "Alpha-2 code": "NP",
    "Alpha-3 code": "NPL",
    "Numeric code": 524,
    Latitude: 28,
    Longitude: 84,
  },
  {
    Country: "Netherlands Antilles",
    "Alpha-2 code": "AN",
    "Alpha-3 code": "ANT",
    "Numeric code": 530,
    Latitude: 12.25,
    Longitude: -68.75,
  },
  {
    Country: "Netherlands",
    "Alpha-2 code": "NL",
    "Alpha-3 code": "NLD",
    "Numeric code": 528,
    Latitude: 52.5,
    Longitude: 5.75,
  },
  {
    Country: "New Caledonia",
    "Alpha-2 code": "NC",
    "Alpha-3 code": "NCL",
    "Numeric code": 540,
    Latitude: -21.5,
    Longitude: 165.5,
  },
  {
    Country: "New Zealand",
    "Alpha-2 code": "NZ",
    "Alpha-3 code": "NZL",
    "Numeric code": 554,
    Latitude: -41,
    Longitude: 174,
  },
  {
    Country: "Nicaragua",
    "Alpha-2 code": "NI",
    "Alpha-3 code": "NIC",
    "Numeric code": 558,
    Latitude: 13,
    Longitude: -85,
  },
  {
    Country: "Niger",
    "Alpha-2 code": "NE",
    "Alpha-3 code": "NER",
    "Numeric code": 562,
    Latitude: 16,
    Longitude: 8,
  },
  {
    Country: "Nigeria",
    "Alpha-2 code": "NG",
    "Alpha-3 code": "NGA",
    "Numeric code": 566,
    Latitude: 10,
    Longitude: 8,
  },
  {
    Country: "Niue",
    "Alpha-2 code": "NU",
    "Alpha-3 code": "NIU",
    "Numeric code": 570,
    Latitude: -19.0333,
    Longitude: -169.8667,
  },
  {
    Country: "Norfolk Island",
    "Alpha-2 code": "NF",
    "Alpha-3 code": "NFK",
    "Numeric code": 574,
    Latitude: -29.0333,
    Longitude: 167.95,
  },
  {
    Country: "Northern Mariana Islands",
    "Alpha-2 code": "MP",
    "Alpha-3 code": "MNP",
    "Numeric code": 580,
    Latitude: 15.2,
    Longitude: 145.75,
  },
  {
    Country: "Norway",
    "Alpha-2 code": "NO",
    "Alpha-3 code": "NOR",
    "Numeric code": 578,
    Latitude: 62,
    Longitude: 10,
  },
  {
    Country: "Oman",
    "Alpha-2 code": "OM",
    "Alpha-3 code": "OMN",
    "Numeric code": 512,
    Latitude: 21,
    Longitude: 57,
  },
  {
    Country: "Pakistan",
    "Alpha-2 code": "PK",
    "Alpha-3 code": "PAK",
    "Numeric code": 586,
    Latitude: 30,
    Longitude: 70,
  },
  {
    Country: "Palau",
    "Alpha-2 code": "PW",
    "Alpha-3 code": "PLW",
    "Numeric code": 585,
    Latitude: 7.5,
    Longitude: 134.5,
  },
  {
    Country: "Palestinian Territory, Occupied",
    "Alpha-2 code": "PS",
    "Alpha-3 code": "PSE",
    "Numeric code": 275,
    Latitude: 32,
    Longitude: 35.25,
  },
  {
    Country: "Panama",
    "Alpha-2 code": "PA",
    "Alpha-3 code": "PAN",
    "Numeric code": 591,
    Latitude: 9,
    Longitude: -80,
  },
  {
    Country: "Papua New Guinea",
    "Alpha-2 code": "PG",
    "Alpha-3 code": "PNG",
    "Numeric code": 598,
    Latitude: -6,
    Longitude: 147,
  },
  {
    Country: "Paraguay",
    "Alpha-2 code": "PY",
    "Alpha-3 code": "PRY",
    "Numeric code": 600,
    Latitude: -23,
    Longitude: -58,
  },
  {
    Country: "Peru",
    "Alpha-2 code": "PE",
    "Alpha-3 code": "PER",
    "Numeric code": 604,
    Latitude: -10,
    Longitude: -76,
  },
  {
    Country: "Philippines",
    "Alpha-2 code": "PH",
    "Alpha-3 code": "PHL",
    "Numeric code": 608,
    Latitude: 13,
    Longitude: 122,
  },
  {
    Country: "Pitcairn",
    "Alpha-2 code": "PN",
    "Alpha-3 code": "PCN",
    "Numeric code": 612,
    Latitude: -24.7,
    Longitude: -127.4,
  },
  {
    Country: "Poland",
    "Alpha-2 code": "PL",
    "Alpha-3 code": "POL",
    "Numeric code": 616,
    Latitude: 52,
    Longitude: 20,
  },
  {
    Country: "Portugal",
    "Alpha-2 code": "PT",
    "Alpha-3 code": "PRT",
    "Numeric code": 620,
    Latitude: 39.5,
    Longitude: -8,
  },
  {
    Country: "Puerto Rico",
    "Alpha-2 code": "PR",
    "Alpha-3 code": "PRI",
    "Numeric code": 630,
    Latitude: 18.25,
    Longitude: -66.5,
  },
  {
    Country: "Qatar",
    "Alpha-2 code": "QA",
    "Alpha-3 code": "QAT",
    "Numeric code": 634,
    Latitude: 25.5,
    Longitude: 51.25,
  },
  {
    Country: "Réunion",
    "Alpha-2 code": "RE",
    "Alpha-3 code": "REU",
    "Numeric code": 638,
    Latitude: -21.1,
    Longitude: 55.6,
  },
  {
    Country: "Romania",
    "Alpha-2 code": "RO",
    "Alpha-3 code": "ROU",
    "Numeric code": 642,
    Latitude: 46,
    Longitude: 25,
  },
  {
    Country: "Russia",
    "Alpha-2 code": "RU",
    "Alpha-3 code": "RUS",
    "Numeric code": 643,
    Latitude: 60,
    Longitude: 100,
  },
  {
    Country: "Russian Federation",
    "Alpha-2 code": "RU",
    "Alpha-3 code": "RUS",
    "Numeric code": 643,
    Latitude: 60,
    Longitude: 100,
  },
  {
    Country: "Rwanda",
    "Alpha-2 code": "RW",
    "Alpha-3 code": "RWA",
    "Numeric code": 646,
    Latitude: -2,
    Longitude: 30,
  },
  {
    Country: "Saint Barthélemy",
    "Alpha-2 code": "BL",
    "Alpha-3 code": "BLM",
    "Numeric code": 652,
    Latitude: 17.897728,
    Longitude: -62.834244,
  },
  {
    Country: "Saint Helena, Ascension and Tristan da Cunha",
    "Alpha-2 code": "SH",
    "Alpha-3 code": "SHN",
    "Numeric code": 654,
    Latitude: -15.9333,
    Longitude: -5.7,
  },
  {
    Country: "Saint Kitts and Nevis",
    "Alpha-2 code": "KN",
    "Alpha-3 code": "KNA",
    "Numeric code": 659,
    Latitude: 17.3333,
    Longitude: -62.75,
  },
  {
    Country: "Saint Lucia",
    "Alpha-2 code": "LC",
    "Alpha-3 code": "LCA",
    "Numeric code": 662,
    Latitude: 13.8833,
    Longitude: -61.1333,
  },
  {
    Country: "Saint Martin (French part)",
    "Alpha-2 code": "MF",
    "Alpha-3 code": "MAF",
    "Numeric code": 663,
    Latitude: 18.075278,
    Longitude: -63.06,
  },
  {
    Country: "Saint Pierre and Miquelon",
    "Alpha-2 code": "PM",
    "Alpha-3 code": "SPM",
    "Numeric code": 666,
    Latitude: 46.8333,
    Longitude: -56.3333,
  },
  {
    Country: "Saint Vincent & the Grenadines",
    "Alpha-2 code": "VC",
    "Alpha-3 code": "VCT",
    "Numeric code": 670,
    Latitude: 13.25,
    Longitude: -61.2,
  },
  {
    Country: "Saint Vincent and the Grenadines",
    "Alpha-2 code": "VC",
    "Alpha-3 code": "VCT",
    "Numeric code": 670,
    Latitude: 13.25,
    Longitude: -61.2,
  },
  {
    Country: "Samoa",
    "Alpha-2 code": "WS",
    "Alpha-3 code": "WSM",
    "Numeric code": 882,
    Latitude: -13.5833,
    Longitude: -172.3333,
  },
  {
    Country: "San Marino",
    "Alpha-2 code": "SM",
    "Alpha-3 code": "SMR",
    "Numeric code": 674,
    Latitude: 43.7667,
    Longitude: 12.4167,
  },
  {
    Country: "Sao Tome and Principe",
    "Alpha-2 code": "ST",
    "Alpha-3 code": "STP",
    "Numeric code": 678,
    Latitude: 1,
    Longitude: 7,
  },
  {
    Country: "Saudi Arabia",
    "Alpha-2 code": "SA",
    "Alpha-3 code": "SAU",
    "Numeric code": 682,
    Latitude: 25,
    Longitude: 45,
  },
  {
    Country: "Senegal",
    "Alpha-2 code": "SN",
    "Alpha-3 code": "SEN",
    "Numeric code": 686,
    Latitude: 14,
    Longitude: -14,
  },
  {
    Country: "Serbia",
    "Alpha-2 code": "RS",
    "Alpha-3 code": "SRB",
    "Numeric code": 688,
    Latitude: 44,
    Longitude: 21,
  },
  {
    Country: "Seychelles",
    "Alpha-2 code": "SC",
    "Alpha-3 code": "SYC",
    "Numeric code": 690,
    Latitude: -4.5833,
    Longitude: 55.6667,
  },
  {
    Country: "Sierra Leone",
    "Alpha-2 code": "SL",
    "Alpha-3 code": "SLE",
    "Numeric code": 694,
    Latitude: 8.5,
    Longitude: -11.5,
  },
  {
    Country: "Singapore",
    "Alpha-2 code": "SG",
    "Alpha-3 code": "SGP",
    "Numeric code": 702,
    Latitude: 1.3667,
    Longitude: 103.8,
  },
  {
    Country: "Sint Maarten (Dutch part)",
    "Alpha-2 code": "SX",
    "Alpha-3 code": "SXM",
    "Numeric code": 534,
    Latitude: 18.033333,
    Longitude: -63.05,
  },
  {
    Country: "Slovakia",
    "Alpha-2 code": "SK",
    "Alpha-3 code": "SVK",
    "Numeric code": 703,
    Latitude: 48.6667,
    Longitude: 19.5,
  },
  {
    Country: "Slovenia",
    "Alpha-2 code": "SI",
    "Alpha-3 code": "SVN",
    "Numeric code": 705,
    Latitude: 46,
    Longitude: 15,
  },
  {
    Country: "Solomon Islands",
    "Alpha-2 code": "SB",
    "Alpha-3 code": "SLB",
    "Numeric code": 90,
    Latitude: -8,
    Longitude: 159,
  },
  {
    Country: "Somalia",
    "Alpha-2 code": "SO",
    "Alpha-3 code": "SOM",
    "Numeric code": 706,
    Latitude: 10,
    Longitude: 49,
  },
  {
    Country: "South Africa",
    "Alpha-2 code": "ZA",
    "Alpha-3 code": "ZAF",
    "Numeric code": 710,
    Latitude: -29,
    Longitude: 24,
  },
  {
    Country: "South Georgia and the South Sandwich Islands",
    "Alpha-2 code": "GS",
    "Alpha-3 code": "SGS",
    "Numeric code": 239,
    Latitude: -54.5,
    Longitude: -37,
  },
  {
    Country: "South Korea",
    "Alpha-2 code": "KR",
    "Alpha-3 code": "KOR",
    "Numeric code": 410,
    Latitude: 37,
    Longitude: 127.5,
  },
  {
    Country: "South Sudan",
    "Alpha-2 code": "SS",
    "Alpha-3 code": "SSD",
    "Numeric code": 728,
    Latitude: 8,
    Longitude: 30,
  },
  {
    Country: "Spain",
    "Alpha-2 code": "ES",
    "Alpha-3 code": "ESP",
    "Numeric code": 724,
    Latitude: 40,
    Longitude: -4,
  },
  {
    Country: "Sri Lanka",
    "Alpha-2 code": "LK",
    "Alpha-3 code": "LKA",
    "Numeric code": 144,
    Latitude: 7,
    Longitude: 81,
  },
  {
    Country: "St. Vincent and the Grenadines",
    "Alpha-2 code": "VC",
    "Alpha-3 code": "VCT",
    "Numeric code": 670,
    Latitude: 13.25,
    Longitude: -61.2,
  },
  {
    Country: "Sudan",
    "Alpha-2 code": "SD",
    "Alpha-3 code": "SDN",
    "Numeric code": 736,
    Latitude: 15,
    Longitude: 30,
  },
  {
    Country: "Suriname",
    "Alpha-2 code": "SR",
    "Alpha-3 code": "SUR",
    "Numeric code": 740,
    Latitude: 4,
    Longitude: -56,
  },
  {
    Country: "Svalbard and Jan Mayen",
    "Alpha-2 code": "SJ",
    "Alpha-3 code": "SJM",
    "Numeric code": 744,
    Latitude: 78,
    Longitude: 20,
  },
  {
    Country: "Swaziland",
    "Alpha-2 code": "SZ",
    "Alpha-3 code": "SWZ",
    "Numeric code": 748,
    Latitude: -26.5,
    Longitude: 31.5,
  },
  {
    Country: "Sweden",
    "Alpha-2 code": "SE",
    "Alpha-3 code": "SWE",
    "Numeric code": 752,
    Latitude: 62,
    Longitude: 15,
  },
  {
    Country: "Switzerland",
    "Alpha-2 code": "CH",
    "Alpha-3 code": "CHE",
    "Numeric code": 756,
    Latitude: 47,
    Longitude: 8,
  },
  {
    Country: "Syrian Arab Republic",
    "Alpha-2 code": "SY",
    "Alpha-3 code": "SYR",
    "Numeric code": 760,
    Latitude: 35,
    Longitude: 38,
  },
  {
    Country: "Taiwan",
    "Alpha-2 code": "TW",
    "Alpha-3 code": "TWN",
    "Numeric code": 158,
    Latitude: 23.5,
    Longitude: 121,
  },
  {
    Country: "Tajikistan",
    "Alpha-2 code": "TJ",
    "Alpha-3 code": "TJK",
    "Numeric code": 762,
    Latitude: 39,
    Longitude: 71,
  },
  {
    Country: "Tanzania, United Republic of",
    "Alpha-2 code": "TZ",
    "Alpha-3 code": "TZA",
    "Numeric code": 834,
    Latitude: -6,
    Longitude: 35,
  },
  {
    Country: "Thailand",
    "Alpha-2 code": "TH",
    "Alpha-3 code": "THA",
    "Numeric code": 764,
    Latitude: 15,
    Longitude: 100,
  },
  {
    Country: "Timor-Leste",
    "Alpha-2 code": "TL",
    "Alpha-3 code": "TLS",
    "Numeric code": 626,
    Latitude: -8.55,
    Longitude: 125.5167,
  },
  {
    Country: "Togo",
    "Alpha-2 code": "TG",
    "Alpha-3 code": "TGO",
    "Numeric code": 768,
    Latitude: 8,
    Longitude: 1.1667,
  },
  {
    Country: "Tokelau",
    "Alpha-2 code": "TK",
    "Alpha-3 code": "TKL",
    "Numeric code": 772,
    Latitude: -9,
    Longitude: -172,
  },
  {
    Country: "Tonga",
    "Alpha-2 code": "TO",
    "Alpha-3 code": "TON",
    "Numeric code": 776,
    Latitude: -20,
    Longitude: -175,
  },
  {
    Country: "Trinidad and Tobago",
    "Alpha-2 code": "TT",
    "Alpha-3 code": "TTO",
    "Numeric code": 780,
    Latitude: 11,
    Longitude: -61,
  },
  {
    Country: "Tunisia",
    "Alpha-2 code": "TN",
    "Alpha-3 code": "TUN",
    "Numeric code": 788,
    Latitude: 34,
    Longitude: 9,
  },
  {
    Country: "Turkey",
    "Alpha-2 code": "TR",
    "Alpha-3 code": "TUR",
    "Numeric code": 792,
    Latitude: 39,
    Longitude: 35,
  },
  {
    Country: "Turkmenistan",
    "Alpha-2 code": "TM",
    "Alpha-3 code": "TKM",
    "Numeric code": 795,
    Latitude: 40,
    Longitude: 60,
  },
  {
    Country: "Turks and Caicos Islands",
    "Alpha-2 code": "TC",
    "Alpha-3 code": "TCA",
    "Numeric code": 796,
    Latitude: 21.75,
    Longitude: -71.5833,
  },
  {
    Country: "Tuvalu",
    "Alpha-2 code": "TV",
    "Alpha-3 code": "TUV",
    "Numeric code": 798,
    Latitude: -8,
    Longitude: 178,
  },
  {
    Country: "Uganda",
    "Alpha-2 code": "UG",
    "Alpha-3 code": "UGA",
    "Numeric code": 800,
    Latitude: 1,
    Longitude: 32,
  },
  {
    Country: "Ukraine",
    "Alpha-2 code": "UA",
    "Alpha-3 code": "UKR",
    "Numeric code": 804,
    Latitude: 49,
    Longitude: 32,
  },
  {
    Country: "United Arab Emirates",
    "Alpha-2 code": "AE",
    "Alpha-3 code": "ARE",
    "Numeric code": 784,
    Latitude: 24,
    Longitude: 54,
  },
  {
    Country: "United Kingdom",
    "Alpha-2 code": "GB",
    "Alpha-3 code": "GBR",
    "Numeric code": 826,
    Latitude: 54,
    Longitude: -2,
  },
  {
    Country: "United States Minor Outlying Islands",
    "Alpha-2 code": "UM",
    "Alpha-3 code": "UMI",
    "Numeric code": 581,
    Latitude: 19.2833,
    Longitude: 166.6,
  },
  {
    Country: "United States",
    "Alpha-2 code": "US",
    "Alpha-3 code": "USA",
    "Numeric code": 840,
    Latitude: 38,
    Longitude: -97,
  },
  {
    Country: "Uruguay",
    "Alpha-2 code": "UY",
    "Alpha-3 code": "URY",
    "Numeric code": 858,
    Latitude: -33,
    Longitude: -56,
  },
  {
    Country: "Uzbekistan",
    "Alpha-2 code": "UZ",
    "Alpha-3 code": "UZB",
    "Numeric code": 860,
    Latitude: 41,
    Longitude: 64,
  },
  {
    Country: "Vanuatu",
    "Alpha-2 code": "VU",
    "Alpha-3 code": "VUT",
    "Numeric code": 548,
    Latitude: -16,
    Longitude: 167,
  },
  {
    Country: "Venezuela, Bolivarian Republic of",
    "Alpha-2 code": "VE",
    "Alpha-3 code": "VEN",
    "Numeric code": 862,
    Latitude: 8,
    Longitude: -66,
  },
  {
    Country: "Venezuela",
    "Alpha-2 code": "VE",
    "Alpha-3 code": "VEN",
    "Numeric code": 862,
    Latitude: 8,
    Longitude: -66,
  },
  {
    Country: "Viet Nam",
    "Alpha-2 code": "VN",
    "Alpha-3 code": "VNM",
    "Numeric code": 704,
    Latitude: 16,
    Longitude: 106,
  },
  {
    Country: "Vietnam",
    "Alpha-2 code": "VN",
    "Alpha-3 code": "VNM",
    "Numeric code": 704,
    Latitude: 16,
    Longitude: 106,
  },
  {
    Country: "Virgin Islands, British",
    "Alpha-2 code": "VG",
    "Alpha-3 code": "VGB",
    "Numeric code": 92,
    Latitude: 18.5,
    Longitude: -64.5,
  },
  {
    Country: "Virgin Islands, U.S.",
    "Alpha-2 code": "VI",
    "Alpha-3 code": "VIR",
    "Numeric code": 850,
    Latitude: 18.3333,
    Longitude: -64.8333,
  },
  {
    Country: "Wallis and Futuna",
    "Alpha-2 code": "WF",
    "Alpha-3 code": "WLF",
    "Numeric code": 876,
    Latitude: -13.3,
    Longitude: -176.2,
  },
  {
    Country: "Western Sahara",
    "Alpha-2 code": "EH",
    "Alpha-3 code": "ESH",
    "Numeric code": 732,
    Latitude: 24.5,
    Longitude: -13,
  },
  {
    Country: "Yemen",
    "Alpha-2 code": "YE",
    "Alpha-3 code": "YEM",
    "Numeric code": 887,
    Latitude: 15,
    Longitude: 48,
  },
  {
    Country: "Zambia",
    "Alpha-2 code": "ZM",
    "Alpha-3 code": "ZMB",
    "Numeric code": 894,
    Latitude: -15,
    Longitude: 30,
  },
  {
    Country: "Zimbabwe",
    "Alpha-2 code": "ZW",
    "Alpha-3 code": "ZWE",
    "Numeric code": 716,
    Latitude: -20,
    Longitude: 30,
  },
];

export let countriesDict: {
  [x: string]: { iso: string; latitude: number; longitude: number };
} = {
  Afghanistan: { iso: "AFG", latitude: 33, longitude: 65 },
  "Åland Islands": { iso: "ALA", latitude: 60.116667, longitude: 19.9 },
  Albania: { iso: "ALB", latitude: 41, longitude: 20 },
  Algeria: { iso: "DZA", latitude: 28, longitude: 3 },
  "American Samoa": { iso: "ASM", latitude: -14.3333, longitude: -170 },
  Andorra: { iso: "AND", latitude: 42.5, longitude: 1.6 },
  Angola: { iso: "AGO", latitude: -12.5, longitude: 18.5 },
  Anguilla: { iso: "AIA", latitude: 18.25, longitude: -63.1667 },
  Antarctica: { iso: "ATA", latitude: -90, longitude: 0 },
  "Antigua and Barbuda": { iso: "ATG", latitude: 17.05, longitude: -61.8 },
  Argentina: { iso: "ARG", latitude: -34, longitude: -64 },
  Armenia: { iso: "ARM", latitude: 40, longitude: 45 },
  Aruba: { iso: "ABW", latitude: 12.5, longitude: -69.9667 },
  Australia: { iso: "AUS", latitude: -27, longitude: 133 },
  Austria: { iso: "AUT", latitude: 47.3333, longitude: 13.3333 },
  Azerbaijan: { iso: "AZE", latitude: 40.5, longitude: 47.5 },
  Bahamas: { iso: "BHS", latitude: 24.25, longitude: -76 },
  Bahrain: { iso: "BHR", latitude: 26, longitude: 50.55 },
  Bangladesh: { iso: "BGD", latitude: 24, longitude: 90 },
  Barbados: { iso: "BRB", latitude: 13.1667, longitude: -59.5333 },
  Belarus: { iso: "BLR", latitude: 53, longitude: 28 },
  Belgium: { iso: "BEL", latitude: 50.8333, longitude: 4 },
  Belize: { iso: "BLZ", latitude: 17.25, longitude: -88.75 },
  Benin: { iso: "BEN", latitude: 9.5, longitude: 2.25 },
  Bermuda: { iso: "BMU", latitude: 32.3333, longitude: -64.75 },
  Bhutan: { iso: "BTN", latitude: 27.5, longitude: 90.5 },
  "Bolivia, Plurinational State of": {
    iso: "BOL",
    latitude: -17,
    longitude: -65,
  },
  Bolivia: { iso: "BOL", latitude: -17, longitude: -65 },
  "Bonaire, Sint Eustatius and Saba": {
    iso: "BES",
    latitude: 12.183333,
    longitude: -68.233333,
  },
  "Bosnia and Herzegovina": { iso: "BIH", latitude: 44, longitude: 18 },
  Botswana: { iso: "BWA", latitude: -22, longitude: 24 },
  "Bouvet Island": { iso: "BVT", latitude: -54.4333, longitude: 3.4 },
  Brazil: { iso: "BRA", latitude: -10, longitude: -55 },
  "British Indian Ocean Territory": {
    iso: "IOT",
    latitude: -6,
    longitude: 71.5,
  },
  "Brunei Darussalam": { iso: "BRN", latitude: 4.5, longitude: 114.6667 },
  Brunei: { iso: "BRN", latitude: 4.5, longitude: 114.6667 },
  Bulgaria: { iso: "BGR", latitude: 43, longitude: 25 },
  "Burkina Faso": { iso: "BFA", latitude: 13, longitude: -2 },
  Burma: { iso: "MMR", latitude: 22, longitude: 98 },
  Burundi: { iso: "BDI", latitude: -3.5, longitude: 30 },
  Cambodia: { iso: "KHM", latitude: 13, longitude: 105 },
  Cameroon: { iso: "CMR", latitude: 6, longitude: 12 },
  Canada: { iso: "CAN", latitude: 60, longitude: -95 },
  "Cape Verde": { iso: "CPV", latitude: 16, longitude: -24 },
  "Cayman Islands": { iso: "CYM", latitude: 19.5, longitude: -80.5 },
  "Central African Republic": { iso: "CAF", latitude: 7, longitude: 21 },
  Chad: { iso: "TCD", latitude: 15, longitude: 19 },
  Chile: { iso: "CHL", latitude: -30, longitude: -71 },
  China: { iso: "CHN", latitude: 35, longitude: 105 },
  "Christmas Island": { iso: "CXR", latitude: -10.5, longitude: 105.6667 },
  "Cocos (Keeling) Islands": {
    iso: "CCK",
    latitude: -12.5,
    longitude: 96.8333,
  },
  Colombia: { iso: "COL", latitude: 4, longitude: -72 },
  Comoros: { iso: "COM", latitude: -12.1667, longitude: 44.25 },
  "Congo, the Democratic Republic of the": {
    iso: "COD",
    latitude: 0,
    longitude: 25,
  },
  Congo: { iso: "COG", latitude: -1, longitude: 15 },
  "Cook Islands": { iso: "COK", latitude: -21.2333, longitude: -159.7667 },
  "Costa Rica": { iso: "CRI", latitude: 10, longitude: -84 },
  "Côte d'Ivoire": { iso: "CIV", latitude: 8, longitude: -5 },
  Croatia: { iso: "HRV", latitude: 45.1667, longitude: 15.5 },
  Cuba: { iso: "CUB", latitude: 21.5, longitude: -80 },
  Curaçao: { iso: "CUW", latitude: 12.166667, longitude: -68.966667 },
  Cyprus: { iso: "CYP", latitude: 35, longitude: 33 },
  "Czech Republic": { iso: "CZE", latitude: 49.75, longitude: 15.5 },
  Denmark: { iso: "DNK", latitude: 56, longitude: 10 },
  Djibouti: { iso: "DJI", latitude: 11.5, longitude: 43 },
  Dominica: { iso: "DMA", latitude: 15.4167, longitude: -61.3333 },
  "Dominican Republic": { iso: "DOM", latitude: 19, longitude: -70.6667 },
  Ecuador: { iso: "ECU", latitude: -2, longitude: -77.5 },
  Egypt: { iso: "EGY", latitude: 27, longitude: 30 },
  "El Salvador": { iso: "SLV", latitude: 13.8333, longitude: -88.9167 },
  "Equatorial Guinea": { iso: "GNQ", latitude: 2, longitude: 10 },
  Eritrea: { iso: "ERI", latitude: 15, longitude: 39 },
  Estonia: { iso: "EST", latitude: 59, longitude: 26 },
  Ethiopia: { iso: "ETH", latitude: 8, longitude: 38 },
  "Falkland Islands (Malvinas)": {
    iso: "FLK",
    latitude: -51.75,
    longitude: -59,
  },
  "Faroe Islands": { iso: "FRO", latitude: 62, longitude: -7 },
  Fiji: { iso: "FJI", latitude: -18, longitude: 175 },
  Finland: { iso: "FIN", latitude: 64, longitude: 26 },
  France: { iso: "FRA", latitude: 46, longitude: 2 },
  "French Guiana": { iso: "GUF", latitude: 4, longitude: -53 },
  "French Polynesia": { iso: "PYF", latitude: -15, longitude: -140 },
  "French Southern Territories": { iso: "ATF", latitude: -43, longitude: 67 },
  Gabon: { iso: "GAB", latitude: -1, longitude: 11.75 },
  Gambia: { iso: "GMB", latitude: 13.4667, longitude: -16.5667 },
  Georgia: { iso: "GEO", latitude: 42, longitude: 43.5 },
  Germany: { iso: "DEU", latitude: 51, longitude: 9 },
  Ghana: { iso: "GHA", latitude: 8, longitude: -2 },
  Gibraltar: { iso: "GIB", latitude: 36.1833, longitude: -5.3667 },
  Greece: { iso: "GRC", latitude: 39, longitude: 22 },
  Greenland: { iso: "GRL", latitude: 72, longitude: -40 },
  Grenada: { iso: "GRD", latitude: 12.1167, longitude: -61.6667 },
  Guadeloupe: { iso: "GLP", latitude: 16.25, longitude: -61.5833 },
  Guam: { iso: "GUM", latitude: 13.4667, longitude: 144.7833 },
  Guatemala: { iso: "GTM", latitude: 15.5, longitude: -90.25 },
  Guernsey: { iso: "GGY", latitude: 49.5, longitude: -2.56 },
  "Guinea-Bissau": { iso: "GNB", latitude: 12, longitude: -15 },
  Guinea: { iso: "GIN", latitude: 11, longitude: -10 },
  Guyana: { iso: "GUY", latitude: 5, longitude: -59 },
  Haiti: { iso: "HTI", latitude: 19, longitude: -72.4167 },
  "Heard Island and McDonald Islands": {
    iso: "HMD",
    latitude: -53.1,
    longitude: 72.5167,
  },
  "Holy See (Vatican City State)": {
    iso: "VAT",
    latitude: 41.9,
    longitude: 12.45,
  },
  Honduras: { iso: "HND", latitude: 15, longitude: -86.5 },
  "Hong Kong": { iso: "HKG", latitude: 22.25, longitude: 114.1667 },
  Hungary: { iso: "HUN", latitude: 47, longitude: 20 },
  Iceland: { iso: "ISL", latitude: 65, longitude: -18 },
  India: { iso: "IND", latitude: 20, longitude: 77 },
  Indonesia: { iso: "IDN", latitude: -5, longitude: 120 },
  "Iran, Islamic Republic of": { iso: "IRN", latitude: 32, longitude: 53 },
  Iraq: { iso: "IRQ", latitude: 33, longitude: 44 },
  Ireland: { iso: "IRL", latitude: 53, longitude: -8 },
  "Isle of Man": { iso: "IMN", latitude: 54.23, longitude: -4.55 },
  Israel: { iso: "ISR", latitude: 31.5, longitude: 34.75 },
  Italy: { iso: "ITA", latitude: 42.8333, longitude: 12.8333 },
  "Ivory Coast": { iso: "CIV", latitude: 8, longitude: -5 },
  Jamaica: { iso: "JAM", latitude: 18.25, longitude: -77.5 },
  Japan: { iso: "JPN", latitude: 36, longitude: 138 },
  Jersey: { iso: "JEY", latitude: 49.21, longitude: -2.13 },
  Jordan: { iso: "JOR", latitude: 31, longitude: 36 },
  Kazakhstan: { iso: "KAZ", latitude: 48, longitude: 68 },
  Kenya: { iso: "KEN", latitude: 1, longitude: 38 },
  Kiribati: { iso: "KIR", latitude: 1.4167, longitude: 173 },
  "Korea, Democratic People's Republic of": {
    iso: "PRK",
    latitude: 40,
    longitude: 127,
  },
  "Korea, Republic of": { iso: "KOR", latitude: 37, longitude: 127.5 },
  Kosovo: { iso: "XKX", latitude: 42.583333, longitude: 21 },
  Kuwait: { iso: "KWT", latitude: 29.3375, longitude: 47.6581 },
  Kyrgyzstan: { iso: "KGZ", latitude: 41, longitude: 75 },
  "Lao People's Democratic Republic": {
    iso: "LAO",
    latitude: 18,
    longitude: 105,
  },
  Latvia: { iso: "LVA", latitude: 57, longitude: 25 },
  Lebanon: { iso: "LBN", latitude: 33.8333, longitude: 35.8333 },
  Lesotho: { iso: "LSO", latitude: -29.5, longitude: 28.5 },
  Liberia: { iso: "LBR", latitude: 6.5, longitude: -9.5 },
  Libya: { iso: "LBY", latitude: 25, longitude: 17 },
  "Libyan Arab Jamahiriya": { iso: "LBY", latitude: 25, longitude: 17 },
  Liechtenstein: { iso: "LIE", latitude: 47.1667, longitude: 9.5333 },
  Lithuania: { iso: "LTU", latitude: 56, longitude: 24 },
  Luxembourg: { iso: "LUX", latitude: 49.75, longitude: 6.1667 },
  Macao: { iso: "MAC", latitude: 22.1667, longitude: 113.55 },
  "Macedonia, the former Yugoslav Republic of": {
    iso: "MKD",
    latitude: 41.8333,
    longitude: 22,
  },
  Madagascar: { iso: "MDG", latitude: -20, longitude: 47 },
  Malawi: { iso: "MWI", latitude: -13.5, longitude: 34 },
  Malaysia: { iso: "MYS", latitude: 2.5, longitude: 112.5 },
  Maldives: { iso: "MDV", latitude: 3.25, longitude: 73 },
  Mali: { iso: "MLI", latitude: 17, longitude: -4 },
  Malta: { iso: "MLT", latitude: 35.8333, longitude: 14.5833 },
  "Marshall Islands": { iso: "MHL", latitude: 9, longitude: 168 },
  Martinique: { iso: "MTQ", latitude: 14.6667, longitude: -61 },
  Mauritania: { iso: "MRT", latitude: 20, longitude: -12 },
  Mauritius: { iso: "MUS", latitude: -20.2833, longitude: 57.55 },
  Mayotte: { iso: "MYT", latitude: -12.8333, longitude: 45.1667 },
  Mexico: { iso: "MEX", latitude: 23, longitude: -102 },
  "Micronesia, Federated States of": {
    iso: "FSM",
    latitude: 6.9167,
    longitude: 158.25,
  },
  "Moldova, Republic of": { iso: "MDA", latitude: 47, longitude: 29 },
  Monaco: { iso: "MCO", latitude: 43.7333, longitude: 7.4 },
  Mongolia: { iso: "MNG", latitude: 46, longitude: 105 },
  Montenegro: { iso: "MNE", latitude: 42, longitude: 19 },
  Montserrat: { iso: "MSR", latitude: 16.75, longitude: -62.2 },
  Morocco: { iso: "MAR", latitude: 32, longitude: -5 },
  Mozambique: { iso: "MOZ", latitude: -18.25, longitude: 35 },
  Myanmar: { iso: "MMR", latitude: 22, longitude: 98 },
  Namibia: { iso: "NAM", latitude: -22, longitude: 17 },
  Nauru: { iso: "NRU", latitude: -0.5333, longitude: 166.9167 },
  Nepal: { iso: "NPL", latitude: 28, longitude: 84 },
  "Netherlands Antilles": { iso: "ANT", latitude: 12.25, longitude: -68.75 },
  Netherlands: { iso: "NLD", latitude: 52.5, longitude: 5.75 },
  "New Caledonia": { iso: "NCL", latitude: -21.5, longitude: 165.5 },
  "New Zealand": { iso: "NZL", latitude: -41, longitude: 174 },
  Nicaragua: { iso: "NIC", latitude: 13, longitude: -85 },
  Niger: { iso: "NER", latitude: 16, longitude: 8 },
  Nigeria: { iso: "NGA", latitude: 10, longitude: 8 },
  Niue: { iso: "NIU", latitude: -19.0333, longitude: -169.8667 },
  "Norfolk Island": { iso: "NFK", latitude: -29.0333, longitude: 167.95 },
  "Northern Mariana Islands": { iso: "MNP", latitude: 15.2, longitude: 145.75 },
  Norway: { iso: "NOR", latitude: 62, longitude: 10 },
  Oman: { iso: "OMN", latitude: 21, longitude: 57 },
  Pakistan: { iso: "PAK", latitude: 30, longitude: 70 },
  Palau: { iso: "PLW", latitude: 7.5, longitude: 134.5 },
  "Palestinian Territory, Occupied": {
    iso: "PSE",
    latitude: 32,
    longitude: 35.25,
  },
  Panama: { iso: "PAN", latitude: 9, longitude: -80 },
  "Papua New Guinea": { iso: "PNG", latitude: -6, longitude: 147 },
  Paraguay: { iso: "PRY", latitude: -23, longitude: -58 },
  Peru: { iso: "PER", latitude: -10, longitude: -76 },
  Philippines: { iso: "PHL", latitude: 13, longitude: 122 },
  Pitcairn: { iso: "PCN", latitude: -24.7, longitude: -127.4 },
  Poland: { iso: "POL", latitude: 52, longitude: 20 },
  Portugal: { iso: "PRT", latitude: 39.5, longitude: -8 },
  "Puerto Rico": { iso: "PRI", latitude: 18.25, longitude: -66.5 },
  Qatar: { iso: "QAT", latitude: 25.5, longitude: 51.25 },
  Réunion: { iso: "REU", latitude: -21.1, longitude: 55.6 },
  Romania: { iso: "ROU", latitude: 46, longitude: 25 },
  Russia: { iso: "RUS", latitude: 60, longitude: 100 },
  "Russian Federation": { iso: "RUS", latitude: 60, longitude: 100 },
  Rwanda: { iso: "RWA", latitude: -2, longitude: 30 },
  "Saint Barthélemy": {
    iso: "BLM",
    latitude: 17.897728,
    longitude: -62.834244,
  },
  "Saint Helena, Ascension and Tristan da Cunha": {
    iso: "SHN",
    latitude: -15.9333,
    longitude: -5.7,
  },
  "Saint Kitts and Nevis": { iso: "KNA", latitude: 17.3333, longitude: -62.75 },
  "Saint Lucia": { iso: "LCA", latitude: 13.8833, longitude: -61.1333 },
  "Saint Martin (French part)": {
    iso: "MAF",
    latitude: 18.075278,
    longitude: -63.06,
  },
  "Saint Pierre and Miquelon": {
    iso: "SPM",
    latitude: 46.8333,
    longitude: -56.3333,
  },
  "Saint Vincent & the Grenadines": {
    iso: "VCT",
    latitude: 13.25,
    longitude: -61.2,
  },
  "Saint Vincent and the Grenadines": {
    iso: "VCT",
    latitude: 13.25,
    longitude: -61.2,
  },
  Samoa: { iso: "WSM", latitude: -13.5833, longitude: -172.3333 },
  "San Marino": { iso: "SMR", latitude: 43.7667, longitude: 12.4167 },
  "Sao Tome and Principe": { iso: "STP", latitude: 1, longitude: 7 },
  "Saudi Arabia": { iso: "SAU", latitude: 25, longitude: 45 },
  Senegal: { iso: "SEN", latitude: 14, longitude: -14 },
  Serbia: { iso: "SRB", latitude: 44, longitude: 21 },
  Seychelles: { iso: "SYC", latitude: -4.5833, longitude: 55.6667 },
  "Sierra Leone": { iso: "SLE", latitude: 8.5, longitude: -11.5 },
  Singapore: { iso: "SGP", latitude: 1.3667, longitude: 103.8 },
  "Sint Maarten (Dutch part)": {
    iso: "SXM",
    latitude: 18.033333,
    longitude: -63.05,
  },
  Slovakia: { iso: "SVK", latitude: 48.6667, longitude: 19.5 },
  Slovenia: { iso: "SVN", latitude: 46, longitude: 15 },
  "Solomon Islands": { iso: "SLB", latitude: -8, longitude: 159 },
  Somalia: { iso: "SOM", latitude: 10, longitude: 49 },
  "South Africa": { iso: "ZAF", latitude: -29, longitude: 24 },
  "South Georgia and the South Sandwich Islands": {
    iso: "SGS",
    latitude: -54.5,
    longitude: -37,
  },
  "South Korea": { iso: "KOR", latitude: 37, longitude: 127.5 },
  "South Sudan": { iso: "SSD", latitude: 8, longitude: 30 },
  Spain: { iso: "ESP", latitude: 40, longitude: -4 },
  "Sri Lanka": { iso: "LKA", latitude: 7, longitude: 81 },
  "St. Vincent and the Grenadines": {
    iso: "VCT",
    latitude: 13.25,
    longitude: -61.2,
  },
  Sudan: { iso: "SDN", latitude: 15, longitude: 30 },
  Suriname: { iso: "SUR", latitude: 4, longitude: -56 },
  "Svalbard and Jan Mayen": { iso: "SJM", latitude: 78, longitude: 20 },
  Swaziland: { iso: "SWZ", latitude: -26.5, longitude: 31.5 },
  Sweden: { iso: "SWE", latitude: 62, longitude: 15 },
  Switzerland: { iso: "CHE", latitude: 47, longitude: 8 },
  "Syrian Arab Republic": { iso: "SYR", latitude: 35, longitude: 38 },
  Taiwan: { iso: "TWN", latitude: 23.5, longitude: 121 },
  Tajikistan: { iso: "TJK", latitude: 39, longitude: 71 },
  "Tanzania, United Republic of": { iso: "TZA", latitude: -6, longitude: 35 },
  Thailand: { iso: "THA", latitude: 15, longitude: 100 },
  "Timor-Leste": { iso: "TLS", latitude: -8.55, longitude: 125.5167 },
  Togo: { iso: "TGO", latitude: 8, longitude: 1.1667 },
  Tokelau: { iso: "TKL", latitude: -9, longitude: -172 },
  Tonga: { iso: "TON", latitude: -20, longitude: -175 },
  "Trinidad and Tobago": { iso: "TTO", latitude: 11, longitude: -61 },
  Tunisia: { iso: "TUN", latitude: 34, longitude: 9 },
  Turkey: { iso: "TUR", latitude: 39, longitude: 35 },
  Turkmenistan: { iso: "TKM", latitude: 40, longitude: 60 },
  "Turks and Caicos Islands": {
    iso: "TCA",
    latitude: 21.75,
    longitude: -71.5833,
  },
  Tuvalu: { iso: "TUV", latitude: -8, longitude: 178 },
  Uganda: { iso: "UGA", latitude: 1, longitude: 32 },
  Ukraine: { iso: "UKR", latitude: 49, longitude: 32 },
  "United Arab Emirates": { iso: "ARE", latitude: 24, longitude: 54 },
  "United Kingdom": { iso: "GBR", latitude: 54, longitude: -2 },
  "United States Minor Outlying Islands": {
    iso: "UMI",
    latitude: 19.2833,
    longitude: 166.6,
  },
  "United States": { iso: "USA", latitude: 38, longitude: -97 },
  Uruguay: { iso: "URY", latitude: -33, longitude: -56 },
  Uzbekistan: { iso: "UZB", latitude: 41, longitude: 64 },
  Vanuatu: { iso: "VUT", latitude: -16, longitude: 167 },
  "Venezuela, Bolivarian Republic of": {
    iso: "VEN",
    latitude: 8,
    longitude: -66,
  },
  Venezuela: { iso: "VEN", latitude: 8, longitude: -66 },
  "Viet Nam": { iso: "VNM", latitude: 16, longitude: 106 },
  Vietnam: { iso: "VNM", latitude: 16, longitude: 106 },
  "Virgin Islands, British": { iso: "VGB", latitude: 18.5, longitude: -64.5 },
  "Virgin Islands, U.S.": {
    iso: "VIR",
    latitude: 18.3333,
    longitude: -64.8333,
  },
  "Wallis and Futuna": { iso: "WLF", latitude: -13.3, longitude: -176.2 },
  "Western Sahara": { iso: "ESH", latitude: 24.5, longitude: -13 },
  Yemen: { iso: "YEM", latitude: 15, longitude: 48 },
  Zambia: { iso: "ZMB", latitude: -15, longitude: 30 },
  Zimbabwe: { iso: "ZWE", latitude: -20, longitude: 30 },
};
